package br.com.siscom.view.compras;

import br.com.adilson.util.PrinterMatrix;
import br.com.siscom.view.ImpressaoView;
import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class ConfirmaCotacaoCompra extends JPanel {
    
    public ConfirmaCotacaoCompra() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("siscomjavaPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT C FROM CotCab C");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        fornecedorQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Fornecedor f");
        fornecedorList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : fornecedorQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        detailScrollPane = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        deleteDetailButton = new javax.swing.JButton();
        newDetailButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codCotCab}"));
        columnBinding.setColumnName("Cod Cot Cab");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataCotCat}"));
        columnBinding.setColumnName("Data Cot Cat");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${forn1}"));
        columnBinding.setColumnName("Forn1");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${forn2}"));
        columnBinding.setColumnName("Forn2");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${forn3}"));
        columnBinding.setColumnName("Forn3");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${forn4}"));
        columnBinding.setColumnName("Forn4");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${forn5}"));
        columnBinding.setColumnName("Forn5");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${condicoes1}"));
        columnBinding.setColumnName("Condicoes1");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${condicoes2}"));
        columnBinding.setColumnName("Condicoes2");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${condicoes3}"));
        columnBinding.setColumnName("Condicoes3");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${condicoes4}"));
        columnBinding.setColumnName("Condicoes4");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${condicoes5}"));
        columnBinding.setColumnName("Condicoes5");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${desconto1}"));
        columnBinding.setColumnName("Desconto1");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${desconto2}"));
        columnBinding.setColumnName("Desconto2");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${desconto3}"));
        columnBinding.setColumnName("Desconto3");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${desconto4}"));
        columnBinding.setColumnName("Desconto4");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${desconto5}"));
        columnBinding.setColumnName("Desconto5");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entrega1}"));
        columnBinding.setColumnName("Entrega1");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entrega2}"));
        columnBinding.setColumnName("Entrega2");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entrega3}"));
        columnBinding.setColumnName("Entrega3");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entrega4}"));
        columnBinding.setColumnName("Entrega4");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entrega5}"));
        columnBinding.setColumnName("Entrega5");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total1}"));
        columnBinding.setColumnName("Total1");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total2}"));
        columnBinding.setColumnName("Total2");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total3}"));
        columnBinding.setColumnName("Total3");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total4}"));
        columnBinding.setColumnName("Total4");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total5}"));
        columnBinding.setColumnName("Total5");
        columnBinding.setColumnClass(Double.class);
        bindingGroup.addBinding(jTableBinding);

        masterScrollPane.setViewportView(masterTable);

        jPanel1.add(masterScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 500, 0));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 70, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 90, -1));

        jLabel1.setText("Código:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel2.setText("Data:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel3.setText("Fornecedor 01:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel4.setText("Fornecedor 02:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel5.setText("Fornecedor 03:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel6.setText("Fornecedor 04:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel7.setText("Fornecedor 05:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 204));
        jTextField3.setEnabled(false);
        jTextField3.setFocusable(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, -1));

        jTextField4.setBackground(new java.awt.Color(255, 255, 204));
        jTextField4.setEnabled(false);
        jTextField4.setFocusable(false);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 90, -1));

        jTextField5.setBackground(new java.awt.Color(255, 255, 204));
        jTextField5.setEnabled(false);
        jTextField5.setFocusable(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 90, -1));

        jTextField6.setBackground(new java.awt.Color(255, 255, 204));
        jTextField6.setEnabled(false);
        jTextField6.setFocusable(false);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 90, -1));

        jTextField7.setBackground(new java.awt.Color(255, 255, 204));
        jTextField7.setEnabled(false);
        jTextField7.setFocusable(false);
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 90, -1));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, -1));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 90, -1));

        jTextField10.setBackground(new java.awt.Color(255, 255, 204));
        jTextField10.setEnabled(false);
        jTextField10.setFocusable(false);
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 90, -1));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 90, -1));

        jTextField12.setBackground(new java.awt.Color(255, 255, 204));
        jTextField12.setEnabled(false);
        jTextField12.setFocusable(false);
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 90, -1));

        jLabel8.setText("Entrega:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel9.setText("Condições:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel10.setText("SubTotal:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel11.setText("Desconto:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel12.setText("Total:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 90, -1));
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, -1));

        jTextField15.setBackground(new java.awt.Color(255, 255, 204));
        jTextField15.setEnabled(false);
        jTextField15.setFocusable(false);
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 90, -1));
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, -1));

        jTextField17.setBackground(new java.awt.Color(255, 255, 204));
        jTextField17.setEnabled(false);
        jTextField17.setFocusable(false);
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 90, -1));
        jPanel1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, -1));
        jPanel1.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 90, -1));

        jTextField20.setBackground(new java.awt.Color(255, 255, 204));
        jTextField20.setEnabled(false);
        jTextField20.setFocusable(false);
        jPanel1.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 90, -1));
        jPanel1.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 90, -1));

        jTextField22.setBackground(new java.awt.Color(255, 255, 204));
        jTextField22.setEnabled(false);
        jTextField22.setFocusable(false);
        jPanel1.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 90, -1));
        jPanel1.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 90, -1));
        jPanel1.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 90, -1));

        jTextField25.setBackground(new java.awt.Color(255, 255, 204));
        jTextField25.setEnabled(false);
        jTextField25.setFocusable(false);
        jPanel1.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 90, -1));
        jPanel1.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 90, -1));

        jTextField27.setBackground(new java.awt.Color(255, 255, 204));
        jTextField27.setEnabled(false);
        jTextField27.setFocusable(false);
        jPanel1.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 90, -1));
        jPanel1.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 90, -1));
        jPanel1.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 90, -1));

        jTextField30.setBackground(new java.awt.Color(255, 255, 204));
        jTextField30.setEnabled(false);
        jTextField30.setFocusable(false);
        jPanel1.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 90, -1));
        jPanel1.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 90, -1));

        jTextField32.setBackground(new java.awt.Color(255, 255, 204));
        jTextField32.setEnabled(false);
        jTextField32.setFocusable(false);
        jPanel1.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 90, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 230));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel2.setLayout(new java.awt.BorderLayout());

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cotDetCollection}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, eLProperty, detailTable);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${qtdeCotDet}"));
        columnBinding.setColumnName("Qtde Cot Det");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${unit1}"));
        columnBinding.setColumnName("Unit1");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${unit2}"));
        columnBinding.setColumnName("Unit2");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${unit3}"));
        columnBinding.setColumnName("Unit3");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${unit4}"));
        columnBinding.setColumnName("Unit4");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${unit5}"));
        columnBinding.setColumnName("Unit5");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total1}"));
        columnBinding.setColumnName("Total1");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total2}"));
        columnBinding.setColumnName("Total2");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total3}"));
        columnBinding.setColumnName("Total3");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total4}"));
        columnBinding.setColumnName("Total4");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total5}"));
        columnBinding.setColumnName("Total5");
        columnBinding.setColumnClass(Double.class);
        jTableBinding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(jTableBinding);

        detailScrollPane.setViewportView(detailTable);

        jPanel2.add(detailScrollPane, java.awt.BorderLayout.CENTER);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 590, 150));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        newButton.setText("Acessar Cotação");
        newButton.addActionListener(formListener);
        jPanel3.add(newButton);

        saveButton.setText("Save");
        saveButton.addActionListener(formListener);
        jPanel3.add(saveButton);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(formListener);
        jPanel3.add(refreshButton);

        deleteDetailButton.setText("Delete");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteDetailButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteDetailButton.addActionListener(formListener);
        jPanel3.add(deleteDetailButton);

        newDetailButton.setText("New");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), newDetailButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        newDetailButton.addActionListener(formListener);
        jPanel3.add(newDetailButton);

        jButton1.setText("Mapa Comparativo");
        jButton1.addActionListener(formListener);
        jPanel3.add(jButton1);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 590, 40));

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == newButton) {
                ConfirmaCotacaoCompra.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton) {
                ConfirmaCotacaoCompra.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                ConfirmaCotacaoCompra.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteDetailButton) {
                ConfirmaCotacaoCompra.this.deleteDetailButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newDetailButton) {
                ConfirmaCotacaoCompra.this.newDetailButtonActionPerformed(evt);
            }
            else if (evt.getSource() == jButton1) {
                ConfirmaCotacaoCompra.this.jButton1ActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    
    private void deleteDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDetailButtonActionPerformed
        int index = masterTable.getSelectedRow();
        br.com.siscom.bean.CotCab C = list.get(masterTable.convertRowIndexToModel(index));
        Collection<br.com.siscom.bean.CotDet> cs = C.getCotDetCollection();
        int[] selected = detailTable.getSelectedRows();
        List<br.com.siscom.bean.CotDet> toRemove = new ArrayList<br.com.siscom.bean.CotDet>(selected.length);
        for (int idx=0; idx<selected.length; idx++) {
            selected[idx] = detailTable.convertRowIndexToModel(selected[idx]);
            int count = 0;
            Iterator<br.com.siscom.bean.CotDet> iter = cs.iterator();
            while (count++ < selected[idx]) iter.next();
            br.com.siscom.bean.CotDet c = iter.next();
            toRemove.add(c);
            entityManager.remove(c);
        }
        cs.removeAll(toRemove);
        masterTable.clearSelection();
        masterTable.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_deleteDetailButtonActionPerformed

    private void newDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDetailButtonActionPerformed
        int index = masterTable.getSelectedRow();
        br.com.siscom.bean.CotCab C = list.get(masterTable.convertRowIndexToModel(index));
        Collection<br.com.siscom.bean.CotDet> cs = C.getCotDetCollection();
        if (cs == null) {
            cs = new LinkedList<br.com.siscom.bean.CotDet>();
            C.setCotDetCollection(cs);
        }
        br.com.siscom.bean.CotDet c = new br.com.siscom.bean.CotDet();
        entityManager.persist(c);
        c.setCotCab(C);
        cs.add(c);
        masterTable.clearSelection();
        masterTable.setRowSelectionInterval(index, index);
        int row = cs.size()-1;
        detailTable.setRowSelectionInterval(row, row);
        detailTable.scrollRectToVisible(detailTable.getCellRect(row, 0, true));
    }//GEN-LAST:event_newDetailButtonActionPerformed
    
    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        br.com.siscom.bean.CotCab C = new br.com.siscom.bean.CotCab();
        entityManager.persist(C);
        list.add(C);
        int row = list.size()-1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
    }//GEN-LAST:event_newButtonActionPerformed
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<br.com.siscom.bean.CotCab> merged = new ArrayList<br.com.siscom.bean.CotCab>(list.size());
            for (br.com.siscom.bean.CotCab C : list) {
                merged.add(entityManager.merge(C));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    PrinterMatrix printer = new PrinterMatrix();

    //Define o tamanho do papel/tela para impressão, aqui 25 linhas e 140 colunas
    printer.setOutSize(60, 140);

    printer.printCharAtCol(1, 1, 140, "=");
    printer.printTextLinCol(2, 1, "T2Ti.com - www.t2ti.com");

    printer.printCharAtCol(3, 1, 140, "=");
    printer.printTextLinCol(4, 1, "SisCom - Compras - Mapa Comparativo de Precos");
    printer.printCharAtCol(5, 1, 140, "-");
    printer.printTextLinCol(6, 1, "Mapa Referente a Cotacao de Numero: " + jTextField1.getText());
    printer.printTextLinCol(6, 120, "Data: " + jTextField2.getText());
    printer.printCharAtCol(7, 1, 140, "-");
    printer.printTextLinCol(8, 1, "Fornecedores");
    printer.printTextLinCol(8, 60, "Condicoes Pagamento");
    printer.printTextLinCol(8, 100, "Prazo de Entrega");
    printer.printCharAtCol(9, 1, 140, "-");
    
    printer.printTextLinCol(10, 1, jTextField3.getText());
    printer.printTextLinCol(11, 1, jTextField4.getText());
    printer.printTextLinCol(12, 1, jTextField5.getText());
    printer.printTextLinCol(13, 1, jTextField6.getText());
    printer.printTextLinCol(14, 1, jTextField7.getText());
    
    printer.printTextLinCol(10, 60, jTextField9.getText());
    printer.printTextLinCol(11, 60, jTextField14.getText());
    printer.printTextLinCol(12, 60, jTextField19.getText());
    printer.printTextLinCol(13, 60, jTextField24.getText());
    printer.printTextLinCol(14, 60, jTextField29.getText());
    
    printer.printTextLinCol(10, 100, jTextField8.getText());
    printer.printTextLinCol(11, 100, jTextField13.getText());
    printer.printTextLinCol(12, 100, jTextField18.getText());
    printer.printTextLinCol(13, 100, jTextField23.getText());
    printer.printTextLinCol(14, 100, jTextField28.getText());

    printer.printCharAtCol(15, 1, 140, "-");

    printer.printTextLinCol(16, 1, "Descricao");
    printer.printTextLinCol(16, 30, "Qtde");
    printer.printTextLinCol(16, 40, "Unit1");
    printer.printTextLinCol(16, 50, "Tot1");
    printer.printTextLinCol(16, 60, "Unit2");
    printer.printTextLinCol(16, 70, "Tot2");
    printer.printTextLinCol(16, 80, "Unit3");
    printer.printTextLinCol(16, 90, "Tot3");
    printer.printTextLinCol(16, 100, "Unit4");
    printer.printTextLinCol(16, 110, "Tot4");
    printer.printTextLinCol(16, 120, "Unit5");
    printer.printTextLinCol(16, 130, "Tot5");
    printer.printTextLinCol(16, 139, "E");
    
    printer.printCharAtCol(17, 1, 140, "-");

    int index = masterTable.getSelectedRow();
    br.com.siscom.bean.CotCab C = list.get(masterTable.convertRowIndexToModel(index));
    Collection<br.com.siscom.bean.CotDet> cs = C.getCotDetCollection();

    int linha = 18;
    for (br.com.siscom.bean.CotDet cotDet : cs) {    

        printer.printTextLinCol(linha, 1, String.valueOf(cotDet.getDescricaoProduto()));
        printer.printTextLinCol(linha, 30, String.valueOf(cotDet.getQtdeCotDet()));
        printer.printTextLinCol(linha, 40, String.valueOf(cotDet.getUnit1()));
        printer.printTextLinCol(linha, 50, String.valueOf(cotDet.getTotal1()));
        printer.printTextLinCol(linha, 60, String.valueOf(cotDet.getUnit2()));
        printer.printTextLinCol(linha, 70, String.valueOf(cotDet.getTotal3()));
        printer.printTextLinCol(linha, 80, String.valueOf(cotDet.getUnit3()));
        printer.printTextLinCol(linha, 90, String.valueOf(cotDet.getTotal3()));
        printer.printTextLinCol(linha, 100, String.valueOf(cotDet.getUnit4()));
        printer.printTextLinCol(linha, 110, String.valueOf(cotDet.getTotal4()));
        printer.printTextLinCol(linha, 120, String.valueOf(cotDet.getUnit5()));
        printer.printTextLinCol(linha, 130, String.valueOf(cotDet.getTotal5()));
        linha++;
    }

    printer.printCharAtCol(++linha, 1, 140, "-");
    printer.printTextLinCol(++linha, 1, "VALOR TOTAL DOS FORNECEDORES");
    printer.printCharAtCol(++linha, 1, 140, "-");

    printer.printTextLinCol(++linha, 1, "Fornecedores");
    printer.printTextLinCol(linha, 60, "SubTotal");
    printer.printTextLinCol(linha, 90, "Desconto");
    printer.printTextLinCol(linha, 120, "Total");

    printer.printCharAtCol(++linha, 1, 140, "-");

    printer.printTextLinCol(++linha, 1, jTextField3.getText());
    printer.printTextLinCol(linha, 60, jTextField10.getText());
    printer.printTextLinCol(linha, 90, jTextField11.getText());
    printer.printTextLinCol(linha, 120, jTextField12.getText());

    printer.printTextLinCol(++linha, 1, jTextField4.getText());
    printer.printTextLinCol(linha, 60, jTextField15.getText());
    printer.printTextLinCol(linha, 90, jTextField16.getText());
    printer.printTextLinCol(linha, 120, jTextField17.getText());
    
    printer.printTextLinCol(++linha, 1, jTextField5.getText());
    printer.printTextLinCol(linha, 60, jTextField20.getText());
    printer.printTextLinCol(linha, 90, jTextField21.getText());
    printer.printTextLinCol(linha, 120, jTextField22.getText());

    printer.printTextLinCol(++linha, 1, jTextField6.getText());
    printer.printTextLinCol(linha, 60, jTextField25.getText());
    printer.printTextLinCol(linha, 90, jTextField26.getText());
    printer.printTextLinCol(linha, 120, jTextField27.getText());
    
    printer.printTextLinCol(++linha, 1, jTextField7.getText());
    printer.printTextLinCol(linha, 60, jTextField30.getText());
    printer.printTextLinCol(linha, 90, jTextField31.getText());
    printer.printTextLinCol(linha, 120, jTextField32.getText());

    printer.printCharAtCol(++linha, 1, 140, "-");

    linha = linha + 4;

    printer.printCharAtCol(++linha, 1, 40, "_");
    printer.printCharAtCol(linha, 50, 90, "_");
    printer.printCharAtCol(linha, 100, 140, "_");

    printer.printTextLinCol(++linha, 1, "GERENCIA");
    printer.printTextLinCol(linha, 50, "DIRETORIA");
    printer.printTextLinCol(linha, 100, "COMPRAS");

    printer.printCharAtCol(++linha, 1, 140, "-");
    
    printer.toFile("impressao.txt");

    String arg[] = {""};
    ImpressaoView.main(arg);
}//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteDetailButton;
    private javax.swing.JScrollPane detailScrollPane;
    private javax.swing.JTable detailTable;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<br.com.siscom.bean.Fornecedor> fornecedorList;
    private javax.persistence.Query fornecedorQuery;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.util.List<br.com.siscom.bean.CotCab> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JButton newDetailButton;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    
    public static void main(final String[] args) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new ConfirmaCotacaoCompra());
                //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
                frame.setTitle(args[0]);
            }
        });
    }

}
